#!/usr/bin/env python3

import sys
from pathlib import Path

# Update the path to match the location of your spawn_entity.py script.
script_path = str(Path(__file__).parent / 'spawn_entity.py')

sys.argv.insert(1, script_path)
exec(open(script_path).read())